---
title: "fyp_study2"
author: "Jinxiao Zhang"
date: "January 25, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load library}
# library(gridExtra)
library(cowplot)
library("kableExtra") # for making nice tables
library(GGally)
library(lme4)
library(lmerTest)
library(tidyverse)
```

```{r set theme}
theme_set(theme_classic() ) #set the theme
```


```{r participant list}
# (server must be mounted with appropriate file path)
bp_path <- "Z:/SBER/SBER1_physio_R56/data/Full_Study/byparticipant_data"
(bp_files <- list.files(bp_path))

# for FYP purpose
# authenticate
gs_auth()
gs_ls()
# import from Google Sheet
ss = gs_title("Study Quality Control: Data Checking")
gs_data_check <- gs_read(ss, ws = 2, range = cell_rows(3:107))
pids <- gs_data_check$`Participant ID`
```

```{r import raw task data}
# create the list of csv files of ER task
ercsvs <- character(0)
list_noS2 <- c() # list of participants who had no S2 .csv files
for(pid in pids){
  # create list of session 2 csvs
  s2path <- sprintf("%s/%s/session2", bp_path, pid)
  s2ls <- list.files(s2path, recursive = T, full.names = T)
  fn <- s2ls[c(grep("InstructedER_[0-9]{4}.*csv$", s2ls), 
               #grep("Instructed_ER_Task.*csv$", s2ls), 
               grep("Instructed_ER.*csv$", s2ls))]
  if(length(fn) > 0){
    #print(c(pid, length(fn)))
    ercsvs <- append(ercsvs, fn)
  }else{
    list_noS2 = append(list_noS2, pid)
  }
}
# sort the No_session2 list
list_noS2 <- sort(list_noS2)
# check the files in the No_session2 list
for(pid in list_noS2){
  # create list of session 2 csvs
  s2path <- sprintf("%s/%s/session2", bp_path, pid)
  s2ls <- list.files(s2path, recursive = T, full.names = T)
  # print the ID and the number of files in the "session2" folder
  print(c(pid,length(s2ls)))
}
# 1275 - copy (2 identical files) --> remove the copy
# 1574 - pt1, pt2 (2 files both only had 38 rows)
# 5767 - 2 files created at different time
# 1754 - 2 files created at different time
# 1016 - V1, V2, V3 (V1 and V2 are empty files though)
# 1023 - files in a subfolder "Random Files and test data" --> remove the files in the subfolder
# 3538 - 2 files created at different time

# remove the wrong files
ercsvs <- ercsvs[c(-grep("copy", ercsvs), # contain "copy"
                   -grep("Random Files", ercsvs))] # in the "Random Files" folder




#import the raw data
agg_df_raw <- mutate_all(read.csv(ercsvs[1]), as.character) #aggregated raw data
for(i in 2:length(ercsvs)){
  # aggregate all csvs into 1 dataframe
  agg_df_raw <- bind_rows(agg_df_raw, mutate_all(read.csv(ercsvs[i]), as.character))
}

```

```{r fatigue and focus in task}

########## check the fatigue/quality rating in task #########

#get the block-wise rating data
fatigue_quality_rating <- agg_df_raw %>% 
  group_by(participant) %>% 
  filter(imageFile == "") %>% 
  select(participant, 
         Fatigue.response, 
         Data_Quality.response, 
         Watch_Quality.response,
         Distract_Quality.response,
         Reappraise_Quality.response) %>% 
  filter(row_number()!= 1) %>% # remove the trial before the first block
  mutate(fatigue = as.numeric(Fatigue.response),
         focus = as.numeric(Data_Quality.response),
         watch_quality = as.numeric(Watch_Quality.response),
         distract_quality = as.numeric(Distract_Quality.response),
         reappraise_quality = as.numeric(Reappraise_Quality.response),
         block = row_number()) %>% 
  filter(block <= 5)

# plot of ratings by block
# fatigue
p_fatigue <- ggplot(fatigue_quality_rating, aes(fatigue))+
  geom_histogram(colour="black", fill="white")+
  #geom_density(alpha=.2, fill="red") +
  facet_wrap(.~block, ncol = 5)+
  labs(title = "fatigue rating by block")
p_focus <- ggplot(fatigue_quality_rating, aes(focus))+
  geom_histogram(colour="black", fill="white")+
  #geom_density(alpha=.2, fill="red") +
  facet_wrap(.~block, ncol = 5)+
  labs(title = "focus rating by block")
p_watch <- ggplot(fatigue_quality_rating, aes(watch_quality))+
  geom_histogram(colour="black", fill="white")+
  #geom_density(alpha=.2, fill="red") +
  facet_wrap(.~block, ncol = 5)+
  labs(title = "watch rating by block")
p_distract <- ggplot(fatigue_quality_rating, aes(distract_quality))+
  geom_histogram(colour="black", fill="white")+
  #geom_density(alpha=.2, fill="red") +
  facet_wrap(.~block, ncol = 5)+
  labs(title = "distract rating by block")
p_reappraise <- ggplot(fatigue_quality_rating, aes(reappraise_quality))+
  geom_histogram(colour="black", fill="white")+
  #geom_density(alpha=.2, fill="red") +
  facet_wrap(.~block, ncol = 5)+
  labs(title = "reappraise rating by block")

plot_grid(p_fatigue, 
             p_focus, 
             p_watch,
             p_distract,
             p_reappraise,
             ncol=1)

# summarize each participant block ratings
fatigue_quality_summary <- fatigue_quality_rating %>% 
  group_by(participant) %>% 
  summarise(fatigue = mean(fatigue, na.rm = T),
            focus = mean(focus, na.rm = T),
            watch_quality = mean(watch_quality, na.rm = T),
            distract_quality = mean(distract_quality, na.rm = T),
            reappraise_quality = mean(reappraise_quality, na.rm = T),
            n = n()) %>% 
  gather(rating_type, score, fatigue:reappraise_quality)

# add levels of rating types
fatigue_quality_summary$rating_type <- factor(fatigue_quality_summary$rating_type,
                                              levels = c("fatigue",
                                                         "focus",
                                                         "watch_quality",
                                                         "distract_quality",
                                                         "reappraise_quality"))

# plot the distribution
ggplot(fatigue_quality_summary, aes(x = score))+
  geom_histogram(aes(y=..density..), colour="black", fill="white")+
  geom_density(alpha=.2, fill="red") +
  facet_wrap(.~rating_type, ncol = 3)

ggplot(fatigue_quality_summary, aes(x = score))+
  geom_histogram(aes(), colour="black", fill="white")+
  facet_wrap(.~rating_type, ncol = 3)


```
```{r create ER task individual-level data}
# create a clean data from the raw data
agg_df <-  agg_df_raw
agg_df$task <- tolower(agg_df$task) #change it to lower case
agg_df$task <- gsub("rethink", "reappraise", agg_df$task) #replace "rethink" with reappraise
#remove unnecessary rows of "instructions"
agg_df <- agg_df %>% 
  filter(imageFile != "")
#force variable type to be numeric
agg_df$NegRating.response <- as.numeric(agg_df$NegRating.response)
agg_df$ArousalRating.response <- as.numeric(agg_df$ArousalRating.response)

# remove participants who had less than 100 trials
agg_df <- agg_df %>% 
  group_by(participant) %>% 
  mutate(n_trial = n()) %>% 
  filter(n_trial > 100)
# change the variable "assign" to "intensity"
names(agg_df)[names(agg_df) == "assign"] <- "intensity"

# check the number of neutral, low, mid, and high trials (trial number = 15 for each condition)
agg_df %>% 
  group_by(participant, task, intensity) %>% 
  tally()

# individual-wise data
df.ER_ind <-  agg_df %>% 
  group_by(participant, task, intensity) %>% 
  summarise(NegRating.response = mean(NegRating.response, na.rm = TRUE),
            ArousalRating.response = mean(ArousalRating.response, na.rm = TRUE))

df.ER_ind$task <- factor(df.ER_ind$task, levels=c('watch', 'reappraise','distract'), ordered=TRUE)
df.ER_ind$intensity <- factor(df.ER_ind$intensity, levels=c('high', 'mid','low', 'ntr'), ordered=TRUE)

################### change scores ####################
#valence ratings changes
temp_val_change <-  df.ER_ind %>% 
  spread(task, NegRating.response) %>% 
  group_by(participant, intensity) %>% 
  summarise(watch_val_rating = sum(watch, na.rm = T), 
            distract_val_rating = sum(distract, na.rm = T), 
            reappraise_val_rating = sum(reappraise, na.rm = T))
#arousal ratings changes
temp_arou_change <-  df.ER_ind %>% 
  spread(task, ArousalRating.response) %>% 
  group_by(participant, intensity) %>% 
  summarise(watch_arou_rating = sum(watch, na.rm = T), 
            distract_arou_rating = sum(distract, na.rm = T), 
            reappraise_arou_rating = sum(reappraise, na.rm = T))
# merge the 2 wide dataframes
df.ER_ind_wide <- merge(temp_val_change, temp_arou_change, 
                       by = c("participant","intensity"))
df.ER_ind_wide <- df.ER_ind_wide %>% 
  mutate(distract_val_change = watch_val_rating - distract_val_rating, 
         reappraise_val_change = watch_val_rating - reappraise_val_rating,
         distract_arou_change = watch_arou_rating - distract_arou_rating, 
         reappraise_arou_change = watch_arou_rating - reappraise_arou_rating,
         picture = ifelse(intensity == "ntr", "ntr", "neg")) #label the trials as eigher "neutral" or "negative
```


```{r check psg files}
linda_folder <- "Z:/SBER/SBER1_physio_R56/SBER_sleepreports_LindaClete/Scored/11.13.18"
destination_folder <- "Z:/SBER/SBER1_physio_R56/data/brux_scored"
# destination_folder <- "/Volumes/gls$/SBER/SBER1_physio_R56/data/brux_scored"

dir_list_scored <- list.dirs(destination_folder)
sleep_dirs <- grep("[0-9]{4}_BP\\.SLP$", dir_list_scored, value = T)

```


```{r PSG data processing}
#report path: Z:\SBER\SBER1_physio_R56\SBER_sleepreports_LindaClete\Scored\11.13.18\ScoredPsgs_Reports\09.27.18
#hynogram export path: Z:\SBER\SBER1_physio_R56\data\brux_scored\raw_exports

# the path of raw PSG data
psg_path = "Z:/SBER/SBER1_physio_R56/data/brux_scored/raw_exports"
# list and select the hypnogram data files
psg_files <- list.files(psg_path, full.names = T)
psg_txt_files <- psg_files[grep("hypno.TXT$", psg_files)]
# get the participant numbers
psg_pids <-  str_sub(psg_txt_files, 
                     str_length(psg_txt_files)-13, 
                     str_length(psg_txt_files)-10)


#### read files and calculate the sleep staging information #####
# the raw psg data fram
df.psg <- data.frame()
# the data frame of psg summary report
df.psg_summary <-  data.frame()

for (j in 1:length(psg_pids)){
  # read a single psg file
  psg <- read.csv(psg_txt_files[j]) %>% 
  rename("stage" = "X.") %>% 
  mutate(pid = psg_pids[j],
    time = row_number()/2) %>% # t - time in minute
    select(pid, stage, time)
  # combine the single psg file to the whole data frame
  df.psg = rbind(df.psg, psg)
  
  
  
  
  #### calculate the PSG report for each participant #######
  # time point of lights out
  time_light_out = 1
  for (i in 1:nrow(psg)){
    if (psg$stage[i] != "?"){
      time_light_out = i/2 
      break
    } 
  }
  # time point of sleep onset
  time_slp_onset = 1
  for (i in (time_light_out*2):nrow(psg)){
    if (psg$stage[i] %in% c("N1", "N2", "N3")){
      time_slp_onset = i/2 
      break
    } 
  }
  # time point of REM onset
  time_rem_onset = 1
  for (i in (time_slp_onset*2):nrow(psg)){
    if(psg$stage[i] == "R"){
      time_rem_onset = i/2 
      break
    }
  }
  # time point of lights on
  time_light_on = 1
  for (i in 1:nrow(psg)){
    if (psg$stage[nrow(psg) +1 - i] != "?"){
      time_light_on = (nrow(psg) +2 - i)/2 
      break
    } 
  }
  # time point of sleep offset
  time_slp_offset = 1
  for (i in (nrow(psg) - time_light_on*2):nrow(psg)){
    if (psg$stage[nrow(psg) +1 - i] %in% c("N1", "N2", "N3", "R")){
      time_slp_offset = (nrow(psg) +2 - i)/2 
      break
    } 
  }
  # total recording time
  psg_trt = nrow(psg)/2
  # time in bed (time available for sleep)
  psg_tib = time_light_on - time_light_out
  # total sleep time
  psg_tst = psg %>% filter(stage %in% c("N1", "N2", "N3", "R")) %>% nrow()/2
  # WASO - wake after sleep onset
  psg_waso = psg %>% 
    filter(time >= time_slp_onset, time < time_light_on) %>% 
    filter(stage == "W") %>% 
    nrow()/2
  # sleep efficiency
  psg_slp_eff = psg_tst/psg_tib
  # sleep onset latency
  psg_slp_latency = time_slp_onset - time_light_out
  # REM latency
  psg_rem_latency = time_rem_onset - time_slp_onset
  # during the sleep period
  psg_sleep <- psg %>% 
    filter(time >= time_slp_onset, time < time_slp_offset) %>% 
    group_by(stage) %>% 
    summarise(duration = n()/2) %>% 
    spread(stage, duration)
  
  # wake during sleep period
  psg_wake = ifelse(is.null(psg_sleep$W[1]), 0, psg_sleep$W[1])
  # N1 sleep
  psg_n1 = ifelse(is.null(psg_sleep$N1[1]), 0, psg_sleep$N1[1])
  psg_n1_perc = psg_n1/psg_tst
  # N2 sleep
  psg_n2 = ifelse(is.null(psg_sleep$N2[1]), 0, psg_sleep$N2[1])
  psg_n2_perc = psg_n2/psg_tst
  # N3 sleep
  psg_n3 = ifelse(is.null(psg_sleep$N3[1]), 0, psg_sleep$N3[1])
  psg_n3_perc = psg_n3/psg_tst
  # REM sleep
  psg_rem = ifelse(is.null(psg_sleep$R[1]), 0, psg_sleep$R[1])
  psg_rem_perc = psg_rem/psg_tst
  
  # contrust the PSG summary for one participant
  psg_summary <- c(psg_pids[j], psg_trt, psg_tib, psg_tst, psg_waso, psg_slp_eff, 
                   psg_slp_latency, psg_rem_latency, psg_wake, psg_n1, psg_n1_perc,
                   psg_n2, psg_n2_perc, psg_n3, psg_n3_perc, psg_rem, psg_rem_perc) %>% 
    as.numeric()
  # combine the single summary to the whoe summary data frame
  df.psg_summary <- rbind(df.psg_summary, psg_summary)
  
  # set variable names of the summary report
  if(j == 1){
    names(df.psg_summary) <- c("pid", "psg_trt", "psg_tib", "psg_tst", "psg_waso",
                               "psg_slp_eff", "psg_slp_latency", "psg_rem_latency",
                               "psg_wake", "psg_n1", "psg_n1_perc", "psg_n2",
                               "psg_n2_perc", "psg_n3", "psg_n3_perc", 
                               "psg_rem", "psg_rem_perc")
  }
  
}

# remove psg summary of participants who only have "?" data points
for (i in 1:nrow(df.psg_summary)){
  if(df.psg_summary$psg_tst[i] == 0) {
    # if their total sleep time = 0 (all data points are ?)
    df.psg_summary[i, 2:17] <- NA # assign NA to all summary statistics except the pid
  }
}
df.psg_summary$pid <- as.character(df.psg_summary$pid)

# mark the labels for stage
df.psg$stage <- factor(df.psg$stage, 
                         levels = c("?", "N1", "N2", "N3", "R", "W"),
                         labels = c("?", "N1", "N2", "N3", "R", "W"))

# # plot the staging data to check
# ggplot(df.psg %>% filter(pid == "2227"), aes(time, stage))+
#   geom_point(alpha = .5, size = 1)

# kable(df.psg_summary, digit = 3)

# write the psg dataset
write_csv(df.psg_summary, "Z:/SBER/SBER1_physio_R56/data/Full_Study/psg_data/psg_summary.csv")
```

```{r combine PSG and ER task data}
glimpse(df.psg_summary)
glimpse(df.ER_ind_wide)

# combine ER task data and PSG data
df.er_psg <- left_join(df.ER_ind_wide, df.psg_summary, 
                       by = c("participant" = "pid"))

```

```{r visualization 1 PSG}
hist(df.psg_summary$psg_tib, main = "PSG time in bed")
hist(df.psg_summary$psg_tst, main = "PSG total sleep time")
hist(df.psg_summary$psg_n3, main = "PSG SWS time")
hist(df.psg_summary$psg_rem, main = "PSG REM sleep time")
hist(df.psg_summary$psg_n3_perc, main = "PSG SWS percentage")
hist(df.psg_summary$psg_rem_perc, main = "PSG REM percentage")

# REM and SWS
p_psg1 <- ggplot(df.psg_summary,
       aes(psg_rem, psg_n3))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM ~ SWS (min)")

p_psg2 <- ggplot(df.psg_summary,
       aes(psg_rem_perc, psg_n3_perc))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM ~ SWS (%)")

# TST and REM
p_psg3 <- ggplot(df.psg_summary,
       aes(psg_rem, psg_tst))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM ~ TST (min)")

# TST and REM
p_psg4 <- ggplot(df.psg_summary,
       aes(psg_n3, psg_tst))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS ~ TST (min)")


## correlation matrix ####
ggpairs(df.er_psg %>%
          filter(intensity == "high") %>% 
          select(psg_tst, psg_n1, psg_n2, psg_n3, psg_rem, 
                 watch_val_rating, watch_arou_rating)) +
  theme_minimal()


ggsave("plots/psg_correlations.png", width = 9, height = 9)
ggsave("plots/psg_reactivity_correlations.png", width = 12, height = 12)

# library(corrplot)
# M <- cor(df.er_psg %>% 
#            filter(intensity == "high") %>% 
#            select(psg_tst, psg_n1, psg_n2, psg_n3, psg_rem) %>% 
#            na.omit())
# corrplot.mixed(M, upper = "ellipse")

```
```{r visualization 2 REM and reactivity}
#### REM and valence-reactivity ####
p_rem1 <- ggplot(df.er_psg,
       aes(psg_rem, watch_val_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM and valence-reactivity (all cases)")

p_rem2 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_rem, watch_val_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM and valence-reactivity (REM>0)")

p_rem3 <- ggplot(df.er_psg,
       aes(psg_rem_perc, watch_val_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM% and valence-reactivity (all cases)")

p_rem4 <- ggplot(df.er_psg %>% filter(psg_rem_perc > 0),
       aes(psg_rem_perc, watch_val_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM% and valence-reactivity (REM>0)")

plot_grid(p_rem1, p_rem2, p_rem3, p_rem4, ncol = 2)
ggsave("plots/rem-valence-reactivity correlation.png", width = 12, height = 9)


#### REM and arousal-reactivity ####
p_rem5 <- ggplot(df.er_psg,
       aes(psg_rem, watch_arou_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM and arousal-reactivity (all cases)")

p_rem6 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_rem, watch_arou_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM and arousal-reactivity (REM>0)")

p_rem7 <- ggplot(df.er_psg,
       aes(psg_rem_perc, watch_arou_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM% and arousal-reactivity (all cases)")

p_rem8 <- ggplot(df.er_psg %>% filter(psg_rem_perc > 0),
       aes(psg_rem_perc, watch_arou_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM% and arousal-reactivity (REM>0)")

plot_grid(p_rem5, p_rem6, p_rem7, p_rem8, ncol = 2)
ggsave("plots/rem-arousal-reactivity correlation.png", width = 12, height = 9)


plot_grid(p_rem1, p_rem5, p_rem3, p_rem7, ncol = 2)
ggsave("plots/rem-reactivity correlation.png", width = 12, height = 9)


```
```{r visualization 3 REM and regulation}
#### REM and regulation of valence ####
p_rem9 <- ggplot(df.er_psg %>% filter(psg_rem >0),
       aes(psg_rem, reappraise_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM and reappraisal-valence change (REM > 0)")

p_rem10 <- ggplot(df.er_psg %>% filter(psg_rem >0),
       aes(psg_rem, distract_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM and distraction-valence change (REM > 0)")

p_rem13 <- ggplot(df.er_psg %>% filter(psg_rem >0),
       aes(psg_rem_perc, reappraise_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM% and reappraisal-valence change (REM > 0)")

p_rem14 <- ggplot(df.er_psg %>% filter(psg_rem >0),
       aes(psg_rem_perc, distract_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM% and distraction-valence change (REM > 0)")



plot_grid(p_rem9, p_rem10, p_rem13, p_rem14)
ggsave("plots/rem-valence-regulation correlation.png", width = 12, height = 9)

#### REM and regulation of arousal ####

p_rem11 <- ggplot(df.er_psg %>% filter(psg_rem >0),
       aes(psg_rem, reappraise_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM and reappraisal-arousal change (REM > 0)")

p_rem12 <- ggplot(df.er_psg %>% filter(psg_rem >0),
       aes(psg_rem, distract_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM and distraction-arousal change (REM > 0)")

p_rem15 <- ggplot(df.er_psg %>% filter(psg_rem >0),
       aes(psg_rem_perc, reappraise_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM% and reappraisal-arousal change (REM > 0)")

p_rem16 <- ggplot(df.er_psg %>% filter(psg_rem >0),
       aes(psg_rem_perc, distract_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "REM% and distraction-arousal change (REM > 0)")

plot_grid(p_rem11, p_rem12, p_rem15, p_rem16)
ggsave("plots/rem-arousal-regulation correlation.png", width = 12, height = 9)
```

```{r visualization 4 SWS and reactivity}
#### SWS and valence-reactivity ####
p_sws1 <- ggplot(df.er_psg,
       aes(psg_n3, watch_val_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS and valence-reactivity")

p_sws2 <- ggplot(df.er_psg ,
       aes(psg_n3_perc, watch_val_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS% and valence-reactivity")

#### SWS and arousal-reactivity ####
p_sws3 <- ggplot(df.er_psg,
       aes(psg_n3, watch_arou_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS and arousal-reactivity")

p_sws4 <- ggplot(df.er_psg,
       aes(psg_n3_perc, watch_arou_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS% and arousal-reactivity")

plot_grid(p_sws1, p_sws3, p_sws2, p_sws4)
ggsave("plots/sws-reactivity correlation2.png", width = 12, height = 9)
```
```{r visualization 5 SWS and regulation}
#### SWS and valence-regulation ####
p_sws5 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_n3, reappraise_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS and reappraisal-valence change (REM > 0)")

p_sws6 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_n3, distract_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS and distract-valence change (REM > 0)")

p_sws7 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_n3_perc, reappraise_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS% and reappraisal-valence change (REM > 0)")

p_sws8 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_n3_perc, distract_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS% and distract-valence change (REM > 0)")

plot_grid(p_sws5, p_sws6, p_sws7, p_sws8)
ggsave("plots/sws-valence-regulation correlation.png", width = 12, height = 9)

#### SWS and arousal-regulation ####
p_sws9 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_n3, reappraise_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS and reappraisal-arousal change (REM > 0)")

p_sws10 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_n3, distract_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS and distract-arousal change (REM > 0)")

p_sws11 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_n3_perc, reappraise_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS% and reappraisal-arousal change (REM > 0)")

p_sws12 <- ggplot(df.er_psg %>% filter(psg_rem > 0),
       aes(psg_n3_perc, distract_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "SWS% and distract-arousal change (REM > 0)")

plot_grid(p_sws9, p_sws10, p_sws11, p_sws12)
ggsave("plots/sws-arousal-regulation correlation.png", width = 12, height = 9)

```

```{r visualization 6 TST}
### TST (total sleep time) and reactivity ####
p_tst1 <- ggplot(df.er_psg,
       aes(psg_tst, watch_val_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "Total sleep time and valence-reactivity")

p_tst2 <- ggplot(df.er_psg,
       aes(psg_tst, watch_arou_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "Total sleep time and arousal-reactivity")

### TST and regulation ####
p_tst3 <- ggplot(df.er_psg,
       aes(psg_tst, reappraise_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "Total sleep time and reappraisal-valence change")

p_tst4 <- ggplot(df.er_psg,
       aes(psg_tst, distract_val_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "Total sleep time and distraction-valence change")

p_tst5 <- ggplot(df.er_psg,
       aes(psg_tst, reappraise_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "Total sleep time and reappraisal-arousal change")

p_tst6 <- ggplot(df.er_psg,
       aes(psg_tst, distract_arou_change, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm")+
  labs(title = "Total sleep time and distraction-arousal change")

plot_grid(p_tst1, p_tst2, p_tst3, p_tst4, p_tst5, p_tst6, ncol = 2)
ggsave("plots/tst-reactivity and regulation correlation2.png", width = 12, height = 13.5)

```

```{r visualization 7: mean-center the raw rating}

ggplot(df.er_psg,
       aes(psg_tst, watch_arou_rating, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm", se = F)+
  geom_smooth(data = df.er_psg,
              aes(psg_tst, watch_arou_rating),
              linetype = 2,
              color = "black",
              method = "lm", se = F)+
  labs(title = "Total sleep time and arousal-reactivity (original)")


ggplot(df.er_psg,
       aes(psg_tst, watch_arou_rating))+
  geom_point(aes(color = intensity), alpha = .8)+
  geom_smooth(data = df.er_psg,
              aes(psg_tst, watch_arou_rating),
              linetype = 2,
              color = "black",
              method = "lm", se = F)+
  labs(title = "Total sleep time and arousal-reactivity (average)")


df.er_psg <- df.er_psg %>% 
  group_by(participant) %>% 
  mutate(watch_arou_rating_ctrd = scale(watch_arou_rating, 
                                        center=T, scale = F),
         watch_arou_rating_scld = scale(watch_arou_rating, 
                                        center=T, scale = T))

ggplot(df.er_psg,
       aes(psg_tst, watch_arou_rating_ctrd, color = intensity))+
  geom_point(alpha = .8)+
  geom_smooth(method = "lm", se = F)+
  geom_smooth(aes(psg_tst, watch_arou_rating_ctrd),
              linetype = 2,
              color = "black",
              method = "lm", se = F)+
  labs(title = "Total sleep time and arousal-reactivity (mean-centered)")


```



```{r analysis: PSG and ER-task correlation}
# REM duration
with(df.er_psg %>% filter(intensity == "low"),
     cor.test(psg_rem, watch_val_rating))
with(df.er_psg %>% filter(intensity == "low"),
     cor.test(psg_rem, watch_arou_rating))
# REM percentage %
with(df.er_psg %>% filter(intensity == "high", psg_rem_perc > 0),
     cor.test(psg_rem_perc, watch_val_rating))
with(df.er_psg %>% filter(intensity == "high", psg_rem_perc > 0),
     cor.test(psg_rem_perc, watch_arou_rating))


# SWS duration
with(df.er_psg %>% filter(intensity == "low"),
     cor.test(psg_n3, watch_val_rating))
with(df.er_psg %>% filter(intensity == "low"),
     cor.test(psg_n3, watch_arou_rating))
# SWS percentage %
with(df.er_psg %>% filter(intensity == "high", psg_rem_perc > 0),
     cor.test(psg_n3_perc, watch_val_rating))
with(df.er_psg %>% filter(intensity == "high", psg_rem_perc > 0),
     cor.test(psg_n3_perc, watch_arou_rating))

# TST duration
with(df.er_psg %>% filter(intensity == "high"),
     cor.test(psg_tst, watch_val_rating))
with(df.er_psg %>% filter(intensity == "high"),
     cor.test(psg_tst, watch_arou_rating))

with(df.er_psg %>% filter(intensity == "mid"),
     cor.test(psg_tst, watch_val_rating))
with(df.er_psg %>% filter(intensity == "mid"),
     cor.test(psg_tst, watch_arou_rating))

with(df.er_psg %>% filter(intensity == "low"),
     cor.test(psg_tst, watch_val_rating))
with(df.er_psg %>% filter(intensity == "low"),
     cor.test(psg_tst, watch_arou_rating))

# TST and regulation
with(df.er_psg %>% filter(intensity == "mid", psg_rem > 0),
     cor.test(psg_tst, reappraise_arou_change))
```
```{r analysis: REM and ER-task linear models}
## DV: valence rating ####
mod_tst1 <- lm(watch_val_rating ~ psg_tst, 
               data = df.er_psg %>% filter(intensity == "high" , psg_rem > 0))
summary(mod_tst1)

mod_rem1 <- lm(watch_val_rating ~ psg_rem, 
               data = df.er_psg %>% filter(intensity == "high" , psg_rem > 0))
summary(mod_rem1)

mod_rem2 <- lm(watch_val_rating ~ psg_tst + psg_rem, 
               data = df.er_psg %>% filter(intensity == "high" , psg_rem > 0))
summary(mod_rem2)

# The Bayes Factor way
mod_rem2_BF <- regressionBF(watch_val_rating ~ psg_tst + psg_rem, 
               data = df.er_psg %>% filter(intensity == "high") %>% na.omit())
plot(mod_rem2_BF)

## interaction effect

# recode the intensity into order ranking
df.er_psg <- df.er_psg %>% 
  mutate(intensity_num = ifelse(intensity == "ntr", 0,
                                ifelse(intensity == "low", 1,
                                       ifelse(intensity == "mid", 2,
                                              ifelse(intensity == "high", 3,
                                                     NA)))))

mod_rem3 <- lmer(watch_val_rating ~ psg_rem+intensity_num + (1|participant), 
               data = df.er_psg )
mod_rem4 <- lmer(watch_val_rating ~ psg_rem*intensity_num + (1|participant), 
               data = df.er_psg)
anova(mod_rem3, mod_rem4)


## DV: arousal rating ####
mod_tst2 <- lm(watch_arou_rating ~ psg_tst, 
               data = df.er_psg %>% filter(intensity == "high" , psg_rem > 0))
summary(mod_tst2)

mod_rem5 <- lm(watch_arou_rating ~ psg_rem, 
               data = df.er_psg %>% filter(intensity == "high" , psg_rem > 0))
summary(mod_rem5)

mod_rem6 <- lm(watch_arou_rating ~ psg_tst + psg_rem, 
               data = df.er_psg %>% filter(intensity == "high"))
summary(mod_rem6)

## interaction effect
mod_rem7 <- lmer(watch_arou_rating ~ psg_rem+intensity_num+ (1|participant), 
               data = df.er_psg)
mod_rem8 <- lmer(watch_arou_rating ~ psg_rem*intensity_num+ (1|participant), 
               data = df.er_psg)
anova(mod_rem7, mod_rem8)
```

```{r analysis: SWS and ER-task linear models}
## DV: valence ratings ####
mod_sws1 <- lm(watch_val_rating ~ psg_n3,
               data = df.er_psg %>% filter(intensity == "high" , psg_rem > 0))
summary(mod_sws1)

mod_sws7 <- lm(watch_val_rating ~ psg_n3 + psg_tst,
               data = df.er_psg %>% filter(intensity == "mid" , psg_rem > 0))
summary(mod_sws7)

# interaction
mod_sws2 <- lmer(watch_val_rating ~ psg_n3+intensity_num + (1|participant), 
               data = df.er_psg)
mod_sws3 <- lmer(watch_val_rating ~ psg_n3*intensity_num + (1|participant), 
               data = df.er_psg)
anova(mod_sws2, mod_sws3)

## DV: arousal ratings ####
mod_sws4 <- lm(watch_arou_rating ~ psg_n3,
               data = df.er_psg %>% filter(intensity == "high" , psg_rem > 0))
summary(mod_sws4)

mod_sws8 <- lm(watch_val_rating ~ psg_n3 + psg_tst,
               data = df.er_psg %>% filter(intensity == "mid" , psg_rem > 0))
summary(mod_sws8)

# interaction
mod_sws5 <- lmer(watch_arou_rating ~ psg_n3+intensity_num + (1|participant), 
               data = df.er_psg)
mod_sws6 <- lmer(watch_arou_rating ~ psg_n3*intensity_num + (1|participant), 
               data = df.er_psg)
anova(mod_sws5, mod_sws6)
```
```{r analyses: TST and ER-task linear models}
## interaction


mod_tst4 <- lmer(watch_val_rating ~ psg_tst*intensity_num + (1|participant), 
               data = df.er_psg)
summary(mod_tst4)

mod_tst4c <- lmer(watch_val_rating ~ psg_tst + intensity_num + (1|participant), 
               data = df.er_psg)
anova(mod_tst4c, mod_tst4)



mod_tst3 <- lmer(watch_arou_rating ~ psg_tst*intensity_num + (1|participant), 
               data = df.er_psg)
summary(mod_tst3)

mod_tst3c <- lmer(watch_arou_rating ~ psg_tst + intensity_num + (1|participant), 
               data = df.er_psg)
anova(mod_tst3c, mod_tst3)
```


```{r analysis: REM vs. SWS}
## compare SWS and REM
lm(watch_val_rating ~ psg_rem + psg_n3, 
   data = df.er_psg %>% filter(intensity == "high", psg_rem > 0)) %>% 
  summary()

lm(watch_arou_rating ~ psg_rem + psg_n3, 
   data = df.er_psg %>% filter(intensity == "high", psg_rem > 0)) %>% 
  summary()
```

```{r simulation}
# simulation dataframe
df.simul <- df.er_psg %>% 
  filter(!is.na(psg_tst), intensity == "high") 


fun.simulate <- function(){
  # reactivity 1: only related to TST
  df.simul$reactivity1 <- df.simul$psg_tst*0.01 + rnorm(41, 0, 1)
  # reactivity 2: related to TST and REM
  df.simul$reactivity2 <- df.simul$psg_tst*0.008 + df.simul$psg_rem*0.01 + rnorm(41, 0, 1)
  
  # ggpairs(df.simul %>% select(psg_tst, psg_rem, psg_rem_perc, reactivity1, reactivity2))
  # ggsave("plots/simulation_correlation.png", width = 8, height = 7)

  m1 <- lm(reactivity1 ~ psg_tst + psg_rem, data = df.simul) %>% tidy()
  m2 <- lm(reactivity1 ~ psg_rem_perc, data = df.simul) %>% tidy()
  m3 <- lm(reactivity2 ~ psg_tst + psg_rem, data = df.simul) %>% tidy()
  m4 <- lm(reactivity2 ~ psg_rem_perc, data = df.simul) %>% tidy()
  
  return(c(m1$p.value[3], m2$p.value[2], m3$p.value[3], m4$p.value[2]))
}

# simulate 1k times
sim_result <- replicate(10000, fun.simulate())


# construc the data fame from the simulated results
sim_result <- t(sim_result) %>% as.tibble()
names(sim_result) <- c("p1_reactivity1", "p2_reactivity1", 
                         "p1_reactivity2", "p2_reactivity2")
sim_result_t <- sim_result %>% 
  gather(p_type, p_value, p1_reactivity1:p2_reactivity2) %>% 
  separate(col = p_type, into = c("p_type", "DV"), sep = "_")

sim_result_t$p_type <- factor(sim_result_t$p_type, levels = c("p2", "p1"))

# summarize p-values
sim_result_t %>% 
  group_by(p_type, DV) %>% 
  summarise(number = sum(p_value < .05),
            rej_rate = number/n()) %>% 
  arrange(DV)



ggplot(sim_result_t, 
       aes(x = p_value))+
  geom_density(aes(fill = p_type), alpha = .3)+
  geom_text(data = data.frame(DV = c("reactivity1", "reactivity2"),
                       text_x = c(.5, .5),
                       text_y = c(5 ,5),
                       text = c("null effect data:\np1 (using tst+rem) rejection rate = .0478\np2 (using rem%) rejection rate = .0343",
                                "REM effect data:\np1 (using tst+rem) rejection rate = .4251\n p2 (using rem%) rejection rate = .4695"),
                       p_type = c("1","2")
                       ),
            aes(text_x, text_y,
                label = text))+
  facet_wrap(DV ~ ., ncol = 1)+
  geom_vline(xintercept = .05, 
             linetype = 2)

ggsave("plots/simulation_distribution.png", width = 8, height = 6)
```


```{r save workspace}
save.image('C:/Users/tepzh/Dropbox/Stanford/FYP/fyp_study2/data/workspace_fyp_study2.Rdata')

```


